### ISSUE TITLE
Fivecentplot development version - AttributeError: 'XAxis' object has no attribute 'iter_ticks' Unexpected exception formatting exception

### ISSUE THREAD

**Issue by hgaonkar** [endangeredoxen/fivecentplots#38]
> python version 3.9.11
> fcp version 0.3.0 installed using "pip install https://github.com/endangeredoxen/fivecentplots/archive/refs/heads/development.zip"

> Command used : fcp.plot(image_loc_df, x='EIT [ms]', y='AG')
> Error message : 
Traceback (most recent call last):
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\TEIV-1\AppData\Local\Temp\ipykernel_15820\2284732138.py", line 1, in <cell line: 1>
    fcp.plot(image_loc_df, x='EIT [ms]', y='AG')
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\fcp.py", line 213, in plot
    return plotter('plot_xy', **dfkwarg(args, kwargs))
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\fcp.py", line 583, in plotter
    layout.make_figure(dd, **kwargs)
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\layout.py", line 2662, in make_figure
    self.get_element_sizes(data)
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\layout.py", line 2023, in get_element_sizes
    xiter_ticks = [f for f in axes[0].xaxis.iter_ticks()] # fails for symlog in 1.5.1
AttributeError: 'XAxis' object has no attribute 'iter_ticks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\interactiveshell.py", line 1982, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\stack_data\core.py", line 698, in lines
    pieces = self.included_pieces
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\stack_data\core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\stack_data\core.py", line 628, in executing_piece
    return only(
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\executing\executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

**Comment by endangeredoxen** [comment]
Version 0.3.0 is very old and I'm not going to support new patches for it.  Let's address with a later version
