### ISSUE TITLE
FCP version 0.5.0 | module 'fivecentplots.data' has no attribute 'XY'

### ISSUE THREAD

**Issue by hgaonkar** [endangeredoxen/fivecentplots#39]
python version 3.9.11
fcp version 0.5.0 
Command used : fcp.plot(image_loc_df, x='EIT [ms]', y='AG')

Error: Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\TEIV-1\AppData\Local\Temp\ipykernel_15820\2284732138.py", line 1, in <cell line: 1>
    fcp.plot(image_loc_df, x='EIT [ms]', y='AG')
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\fcp.py", line 272, in plot
    return plotter(data.XY, **dfkwarg(args, kwargs))
AttributeError: module 'fivecentplots.data' has no attribute 'XY'

**Comment by endangeredoxen** [comment]
Can you please pull the latest updates to 0.5.0 branch and try again?
