### ISSUE TITLE
FCP version 0.4.3 | 'Line2D' object has no attribute '_legmarker' error

### ISSUE THREAD

**Issue by hgaonkar** [endangeredoxen/fivecentplots#40]
python version 3.9.11
fcp version 0.4.3
Command used : fcp.plot(image_loc_df, x='EIT [ms]', y='AG', legend='DG')

AG, DG, and EIT [ms] are all float64 . 
Works fine without legend option. 

Error: 
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\TEIV-1\AppData\Local\Temp\ipykernel_15820\742559488.py", line 1, in <cell line: 1>
    fcp.plot(image_loc_df, x='EIT [ms]', y='AG', legend='DG')
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\fcp.py", line 233, in plot
    return plotter('plot_xy', **dfkwarg(args, kwargs))
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\fcp.py", line 735, in plotter
    dd = layout.make_figure(dd, **kwargs)
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\engines\mpl.py", line 1619, in make_figure
    data = self.get_element_sizes(data)
  File "C:\Users\TEIV-1\miniconda3\envs\imagecrunch\lib\site-packages\fivecentplots\engines\mpl.py", line 1042, in get_element_sizes
    leg.legendHandles[irow]._legmarker\
AttributeError: 'Line2D' object has no attribute '_legmarker'

**Comment by endangeredoxen** [comment]
What version of matplotlib are you using?

**Comment by hgaonkar** [comment]
A fresh install of python solves this issue.

**Comment by hgaonkar** [comment]
Unfortunately, this is a recurring error. On a more recent fresh python install, I received this error. Maybe something to do with installation using miniconda vs anaconda. Not sure. Either way, I updated to 0.5.0 and error goes away.

**Comment by endangeredoxen** [comment]
I'm focused on getting 0.5.0 ready for alpha release so I can't debug this right now.  I suspect it comes from you using a newer version of MPL that was never tested with fcp 0.4.3.  Will revisit this later

**Comment by endangeredoxen** [comment]
Fixed this for v0.5.0
